@startuml
class SpelarePoäng {
    + namn : string <<get>> <<set>>
    + poäng : int <<get>> <<set>>
    + datum : DateTime <<get>> <<set>>
}
class Program {
    {static} Main(args:string[]) : void
}
@enduml
