@startuml
!theme plain
skinparam classAttributeIconSize 0
hide circle
class Boklån {
    + bok : string
    + låntagare : string
    + datum : DateTime
    + LämnasTillbaka() : DateTime
    + DagarKvar() : int
    + SkrivUt() : void
}
@enduml
