@startuml
class Tamagotchi {
    - hunger : int
    - boredom : int
    - words : List<string>
    - isAlive : bool
    - generator : Random
    + name : string
    + Tamagotchi(name:string)
    + Feed() : void
    + Hi() : void
    + Teach(word:string) : void
    + Tick() : void
    + PrintStats() : void
    + GetAlive() : bool
    - ReduceBoredom() : void
}
@enduml
